apiVersion: app.fybrik.io/v1alpha1
kind: FybrikApplication
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  selector:
    workloadSelector:
      matchLabels:
        app: my-app
  appInfo:
    intent: Fraud Detection
  data:
    - dataSetID: "fybrik-airbyte-sample/userdata"
      requirements:
        interface:
          protocol: fybrik-arrow-flight
